# Generated by Django 5.0.6 on 2024-07-09 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='contactNo',
            field=models.TextField(default=''),
        ),
    ]
