# Generated by Django 5.0.6 on 2024-07-09 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_student_contactno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='placed',
            field=models.CharField(default='No'),
        ),
    ]
