# Generated by Django 5.0.6 on 2024-07-13 15:52

import main.constants
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_student_placed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='companies',
        ),
        migrations.AddField(
            model_name='interview',
            name='status',
            field=models.CharField(default=main.constants.CompanyStatus['SCHEDULED'], max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='appliedCompanies',
            field=models.ManyToManyField(blank=True, related_name='applied_students', to='main.interview'),
        ),
        migrations.AddField(
            model_name='student',
            name='placedCompanies',
            field=models.ManyToManyField(blank=True, related_name='placed_students', to='main.interview'),
        ),
    ]
