# Generated by Django 5.0.6 on 2024-07-13 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_student_companies_interview_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='status',
            field=models.CharField(default='Scheduled', max_length=100),
        ),
    ]
