# Generated by Django 5.0.6 on 2024-07-17 15:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_interview_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='student',
            name='placed',
            field=models.CharField(default='No', max_length=3),
        ),
        migrations.AlterField(
            model_name='student',
            name='registerNo',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
